version: '3.4'

services:
  sombra.web:
    image: sombra.web
    build:
      context: .
      dockerfile: Sombra.Web/Dockerfile
    depends_on:
      - rabbitmq

  sombra.charityservice:
    image: sombra.charityservice
    build:
      context: .
      dockerfile: Sombra.CharityService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.charityactionservice:
    image: sombra.charityactionservice
    build:
      context: .
      dockerfile: Sombra.CharityActionService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.emailservice:
    image: sombra.emailservice
    build:
      context: .
      dockerfile: Sombra.EmailService/Dockerfile
    depends_on:
      - rabbitmq
  
  sombra.identityservice:
    image: sombra.identityservice
    build:
      context: .
      dockerfile: Sombra.IdentityService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
      
  sombra.templateservice:
    image: sombra.templateservice
    build:
      context: .
      dockerfile: Sombra.TemplateService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.userservice:
    image: sombra.userservice
    build:
      context: .
      dockerfile: Sombra.UserService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.donateservice:
    image: sombra.donateservice
    build:
      context: .
      dockerfile: Sombra.DonateService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.loggingservice:
    image: sombra.loggingservice
    build:
      context: .
      dockerfile: Sombra.LoggingService/Dockerfile
    depends_on:
      - rabbitmq
      - mongoserver

  sombra.searchservice:
    image: sombra.searchservice
    build:
      context: .
      dockerfile: Sombra.SearchService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.timeservice:
    image: sombra.timeservice
    build:
      context: .
      dockerfile: Sombra.TimeService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.storyservice:
    image: sombra.storyservice
    build:
      context: .
      dockerfile: Sombra.StoryService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 

  mongoserver:
    image: mongo
    container_name: mongoserver
    volumes:
      - mongoserverdata:/data/db


volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true
  mongoserverdata:
    external: true
  portainerdata:
    external: true
