version: '3.4'

services:
  sombra.web:
    environment:
      - CONTAINER_TYPE=Docker
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
    ports:
      - "80:80"
 
  sombra.charityservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - CHARITY_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Charities;

  sombra.charityactionservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - CHARITYACTION_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=CharityActions;

  sombra.emailservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - SMTP_SERVER=${DC_SMTPSERVER}
      - SMTP_PORT=${DC_SMTPPORT}
      - SMTP_USERNAME=${DC_SMTPUSERNAME}
      - SMTP_PASSWORD=${DC_SMTPPASSWORD}

  sombra.loggingservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - MONGO_CONNECTIONSTRING=mongodb://${DC_MONGOUSER:-mongouser}:${DC_MONGOPASSWORD:-mongopassword}@${DC_MONGOHOST:-mongoserver}/
      - MONGO_DATABASE=logging

  sombra.identityservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - AUTHENTICATION_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Authentication;

  sombra.templateservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - TEMPLATE_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Templates;

  sombra.userservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - USER_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Users;

  sombra.searchservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - SEARCH_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Search;

  sombra.timeservice:
    environment:
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - TIME_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Time;


  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=${DC_RABBITMQUSER:-rabbitmquser}
      - RABBITMQ_DEFAULT_PASS=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
    ports:
      - "15672:15672"
      - "5672:5672"
  
  sqlserver:
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=${DC_SQLPASSWORD:-HPlab1718}
    ports:
      - "1434:1433"
  
  mongoserver:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DC_MONGOUSER:-mongouser}
      - MONGO_INITDB_ROOT_PASSWORD=${DC_MONGOPASSWORD:-mongopassword}
    ports:
      - "27017:27017"


  portainer:
    ports:
      - "9000:9000"