version: '3'

services:
  sombra.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
    ports:
      - "80:80"
  
  sombra.emailservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONTAINER_TYPE=Docker
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - SMTP_SERVER=${DC_SMTPSERVER}
      - SMTP_PORT=${DC_SMTPPORT}
      - SMTP_USERNAME=${DC_SMTPUSERNAME}
      - SMTP_PASSWORD=${DC_SMTPPASSWORD}

  sombra.identityservice:
    environment:
      - CONTAINER_TYPE=Docker
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - AUTHENTICATION_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Authentication;

  sombra.templateservice:
    environment:
      - CONTAINER_TYPE=Docker
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - TEMPLATE_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Templates;

  sombra.userservice:
    environment:
      - CONTAINER_TYPE=Docker
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_CONNECTIONSTRING=host=${DC_RABBITMQHOST:-rabbitmq};username=${DC_RABBITMQUSER:-rabbitmquser};password=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
      - USER_DB_CONNECTIONSTRING=server=${DC_SQLHOST:-sqlserver};user id=${DC_SQLUSER:-sa};password=${DC_SQLPASSWORD:-HPlab1718};database=Users;

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=${DC_RABBITMQUSER:-rabbitmquser}
      - RABBITMQ_DEFAULT_PASS=${DC_RABBITMQPASSWORD:-rabbitmqpassword}
    ports:
      - "15672:15672"
      - "5672:5672"
  
  sqlserver:
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=${DC_SQLPASSWORD:-HPlab1718}
    ports:
      - "1434:1433"

  portainer:
    ports:
      - "9000:9000"