version: '3'

services:
  sombra.web:
    image: sombra.web
    build:
      context: .
      dockerfile: Sombra.Web/Dockerfile
    depends_on:
      - rabbitmq

  sombra.web.unittests:
    image: sombra.web.unittests
    build:
      context: .
      dockerfile: Sombra.Web.UnitTests/Dockerfile


  sombra.core.unittests:
    image: sombra.core.unittests
    build:
      context: .
      dockerfile: Sombra.Core.UnitTests/Dockerfile


  sombra.emailservice:
    image: sombraemailservice
    build:
      context: .
      dockerfile: Sombra.EmailService/Dockerfile
    depends_on:
      - rabbitmq


  sombra.loggingservice:
    image: sombraloggingservice
    build:
      context: .
      dockerfile: Sombra.LoggingService/Dockerfile
    depends_on:
      - rabbitmq
      - mongoserver


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq


  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver


  mongoserver:
    image: mongo
    container_name: mongoserver