version: '3'

services:
  sombra.web:
    image: sombra.web
    build:
      context: .
      dockerfile: Sombra.Web/Dockerfile
    depends_on:
      - rabbitmq

  sombra.emailservice:
    image: sombra.emailservice
    build:
      context: .
      dockerfile: Sombra.EmailService/Dockerfile
    depends_on:
      - rabbitmq
  
  sombra.identityservice:
    image: sombra.identityservice
    build:
      context: .
      dockerfile: Sombra.IdentityService/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver


  sombra.loggingservice:
    image: sombra.loggingservice
    build:
      context: .
      dockerfile: Sombra.LoggingService/Dockerfile
    depends_on:
      - rabbitmq
      - mongoserver


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq


  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver

  mongoserver:
    image: mongo
    container_name: mongoserver
    volumes:
      - mongoserverdata:/data/db


  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    command: --admin-password "$$2y$$05$$oqKhCttN2CNtXdtgFzoUYOrGH.MyqRsk8he2coY4IniTOjjBFwOw."
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data portainer/portainer


volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true
  mongoserverdata:
    external: true
  portainerdata:
    external: true
