version: '3'

services:
  sombra.web:
    image: sombra.web
    build:
      context: .
      dockerfile: Sombra.Web/Dockerfile

  sombra.web.unittests:
    image: sombra.web.unittests
    build:
      context: .
      dockerfile: Sombra.Web.UnitTests/Dockerfile

