version: '3.4'

services:
  sombra.web:
    depends_on:
      - rabbitmq

  sombra.charityservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.charityactionservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.emailservice:
    depends_on:
      - rabbitmq

  sombra.idendityservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.templateservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.userservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.donateservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.loggingservice:
    depends_on:
      - rabbitmq
      - mongoserver

  sombra.searchservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.timeservice:
    depends_on:
      - rabbitmq
      - sqlserver

  sombra.storyservice:
    depends_on:
      - rabbitmq
      - sqlserver

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 

  mongoserver:
    image: mongo
    container_name: mongoserver
    volumes:
      - mongoserverdata:/data/db

  portainer:
    image: portainer/portainer
    container_name: portainer-app
    command: --admin-password "$$2y$$05$$oqKhCttN2CNtXdtgFzoUYOrGH.MyqRsk8he2coY4IniTOjjBFwOw."
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data portainer/portainer


volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true
  mongoserverdata:
    external: true
  portainerdata:
    external: true
