version: '3.4'

services:
  sombra.web.unittests:
    image: sombra.web.unittests
    build:
      context: .
      dockerfile: Sombra.Web.UnitTests/Dockerfile

  sombra.core.unittests:
    image: sombra.core.unittests
    build:
      context: .
      dockerfile: Sombra.Core.UnitTests/Dockerfile

  sombra.charityservice.unittests:
    image: sombra.charityservice.unittests
    build:
      context: .
      dockerfile: Sombra.CharityService.UnitTests/Dockerfile

  sombra.emailservice.unittests:
    image: sombra.emailservice.unittests
    build:
      context: .
      dockerfile: Sombra.EmailService.UnitTests/Dockerfile

  sombra.identityservice.unittests:
    image: sombra.identityservice.unittests
    build:
      context: .
      dockerfile: Sombra.IdentityService.UnitTests/Dockerfile

  sombra.templateservice.unittests:
    image: sombra.templateservice.unittests
    build:
      context: .
      dockerfile: Sombra.TemplateService.UnitTests/Dockerfile

  sombra.userservice.unittests:
    image: sombra.userservice.unittests
    build:
      context: .
      dockerfile: Sombra.UserService.UnitTests/Dockerfile

  sombra.searchservice.unittests:
    image: sombra.searchservice.unittests
    build:
      context: .
      dockerfile: Sombra.SearchService.UnitTests/Dockerfile

