version: '3'

services:
  sombra.web:
    image: sombra.web
    build:
      context: .
      dockerfile: Sombra.Web/Dockerfile

  sombra.web.unittests:
    image: sombra.web.unittests
    build:
      context: .
      dockerfile: Sombra.Web.UnitTests/Dockerfile


  sombra.core.unittests:
    image: sombra.core.unittests
    build:
      context: .
      dockerfile: Sombra.Core.UnitTests/Dockerfile


  sombra.emailservice:
    image: sombraemailservice
    build:
      context: .
      dockerfile: Sombra.EmailService/Dockerfile

